"""Initial database schema

Revision ID: 0b87743f0285
Revises: 
Create Date: 2025-12-31 09:07:15.881624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b87743f0285'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_items', 'guid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_feed_items_guid'), table_name='feed_items')
    op.create_unique_constraint(None, 'feed_items', ['guid'])
    op.alter_column('feeds', 'last_fetch_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('feeds', 'sort_order')
    op.drop_column('feeds', 'category_icon')
    op.drop_column('feeds', 'category_sort_order')
    op.alter_column('preset_integrations', 'default_favcat',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preset_integrations', 'default_favcat',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('feeds', sa.Column('category_sort_order', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('feeds', sa.Column('category_icon', sa.TEXT(), server_default=sa.text("'icon:Folder'"), nullable=True))
    op.add_column('feeds', sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.alter_column('feeds', 'last_fetch_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'feed_items', type_='unique')
    op.create_index(op.f('idx_feed_items_guid'), 'feed_items', ['guid'], unique=1)
    op.alter_column('feed_items', 'guid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
